In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('scraping olx.xlsx')

In [ ]:
df

,Product Name,Price,Year-km,Locations
0,Daihatsu Sirion,Rp 125.000.000,2017 - 155.000-160.000 km,Pasar MingguHari ini
1,Toyota Agya,Rp 109.000.000,2019 - 30.000-35.000 km,PesanggrahanHari ini
2,Wuling Cortez,Rp 162.000.000,2021 - 55.000-60.000 km,Kebayoran LamaHari ini
3,Mitsubishi Outlander Sport,Rp 169.000.000,2015 - 115.000-120.000 km,Pasar MingguHari ini
4,Honda Brio Satya,Rp 123.000.000,2017 - 85.000-90.000 km,Pancoran6 hari yang lalu
...,...,...,...,...
509,Toyota Yaris,Rp 109.000.000,2012 - 90.000-95.000 km,Kebayoran LamaHari ini
510,Toyota Agya,Rp 100.000.000,2015 - 65.000-70.000 km,PancoranHari ini
511,Suzuki Sidekick,Rp 75.000.000,1998 - 70.000-75.000 km,Kebayoran LamaHari ini
512,Toyota Yaris,Rp 113.000.000,2011 - 35.000-40.000 km,CilandakHari ini
513,Nissan March,Rp 86.500.000,2012 - 90.000-95.000 km,CilandakHari ini

In [ ]:
df = df.rename(columns={'Product Name' : 'Type'})

In [ ]:
df[['Year', 'Kilometres']] = df['Year-km'].str.split('-', n=1, expand=True)

In [ ]:
df

,Type,Price,Year-km,Locations,Year,Kilometres
0,Daihatsu Sirion,Rp 125.000.000,2017 - 155.000-160.000 km,Pasar MingguHari ini,2017,155.000-160.000 km
1,Toyota Agya,Rp 109.000.000,2019 - 30.000-35.000 km,PesanggrahanHari ini,2019,30.000-35.000 km
2,Wuling Cortez,Rp 162.000.000,2021 - 55.000-60.000 km,Kebayoran LamaHari ini,2021,55.000-60.000 km
3,Mitsubishi Outlander Sport,Rp 169.000.000,2015 - 115.000-120.000 km,Pasar MingguHari ini,2015,115.000-120.000 km
4,Honda Brio Satya,Rp 123.000.000,2017 - 85.000-90.000 km,Pancoran6 hari yang lalu,2017,85.000-90.000 km
...,...,...,...,...,...,...
509,Toyota Yaris,Rp 109.000.000,2012 - 90.000-95.000 km,Kebayoran LamaHari ini,2012,90.000-95.000 km
510,Toyota Agya,Rp 100.000.000,2015 - 65.000-70.000 km,PancoranHari ini,2015,65.000-70.000 km
511,Suzuki Sidekick,Rp 75.000.000,1998 - 70.000-75.000 km,Kebayoran LamaHari ini,1998,70.000-75.000 km
512,Toyota Yaris,Rp 113.000.000,2011 - 35.000-40.000 km,CilandakHari ini,2011,35.000-40.000 km
513,Nissan March,Rp 86.500.000,2012 - 90.000-95.000 km,CilandakHari ini,2012,90.000-95.000 km

In [ ]:
df['Kilometres'] = df['Kilometres'].str.replace(' km', '')

In [ ]:
df['Kilometres'] = df['Kilometres'].str.replace(r'(\d+)-(\d+)', r'\1 - \2')

<ipython-input-275-479997c36505>:1: FutureWarning: The default value of regex will change from True to False in a future version.
  df['Kilometres'] = df['Kilometres'].str.replace(r'(\d+)-(\d+)', r'\1 - \2')

In [ ]:
df['Year'] = df['Year'].str.replace(' ', '')
df['Year'] = df['Year'].str.replace('<', '')

In [ ]:
df = df.drop('Year-km', axis=1)

In [ ]:
df

,Type,Price,Locations,Year,Kilometres
0,Daihatsu Sirion,Rp 125.000.000,Pasar MingguHari ini,2017,155.000 - 160.000
1,Toyota Agya,Rp 109.000.000,PesanggrahanHari ini,2019,30.000 - 35.000
2,Wuling Cortez,Rp 162.000.000,Kebayoran LamaHari ini,2021,55.000 - 60.000
3,Mitsubishi Outlander Sport,Rp 169.000.000,Pasar MingguHari ini,2015,115.000 - 120.000
4,Honda Brio Satya,Rp 123.000.000,Pancoran6 hari yang lalu,2017,85.000 - 90.000
...,...,...,...,...,...
509,Toyota Yaris,Rp 109.000.000,Kebayoran LamaHari ini,2012,90.000 - 95.000
510,Toyota Agya,Rp 100.000.000,PancoranHari ini,2015,65.000 - 70.000
511,Suzuki Sidekick,Rp 75.000.000,Kebayoran LamaHari ini,1998,70.000 - 75.000
512,Toyota Yaris,Rp 113.000.000,CilandakHari ini,2011,35.000 - 40.000
513,Nissan March,Rp 86.500.000,CilandakHari ini,2012,90.000 - 95.000

In [ ]:
df['Locations'].unique()

array(['Pasar MingguHari ini', 'PesanggrahanHari ini',
       'Kebayoran LamaHari ini', 'Pancoran6 hari yang lalu',
       'Cilandak08 Mar', 'Pasar Minggu08 Mar', 'Cilandak5 hari yang lalu',
       'Kebayoran BaruHari ini', 'CilandakHari ini', 'PancoranHari ini',
       'Mampang PrapatanHari ini', 'Cilandak14 Mar',
       'Kebayoran Lama3 hari yang lalu', 'Cilandak17 Mar',
       'Cilandak02 Mar', 'Cilandak07 Mar', 'Kebayoran Lama14 Feb',
       'Kebayoran Lama4 hari yang lalu', 'Jakarta SelatanHari ini',
       'Kebayoran Baru15 Mar', 'Cilandak05 Mar', 'Kebayoran Lama11 Des',
       'Cilandak4 hari yang lalu', 'Kebayoran Baru12 Mar',
       'Cilandak12 Mar', 'Kebayoran Baru04 Mar',
       'Jakarta Selatan2 hari yang lalu', 'Pasar Minggu10 Mar',
       'Pancoran5 hari yang lalu', 'Cilandak25 Feb',
       'Kebayoran Baru01 Mar', 'Kebayoran Lama22 Jan',
       'Kebayoran Lama12 Mar', 'Kebayoran Baru22 Feb', 'Cilandak15 Mar',
       'PancoranKemarin', 'Cilandak09 Mar', 'Kebayoran Baru08 Mar',
       'Cilandak11 Feb', 'Kebayoran Baru19 Feb', 'Cilandak22 Feb',
       'Kebayoran Baru18 Des', 'Cilandak16 Mar', 'Kebayoran Baru20 Jan',
       'Kebayoran Baru23 Feb', 'Pasar Minggu01 Mar',
       'Jakarta Selatan05 Mar', 'Kebayoran Baru06 Mar',
       'Kebayoran Baru4 hari yang lalu', 'Cilandak3 hari yang lalu',
       'Kebayoran Baru2 hari yang lalu', 'Kebayoran Lama26 Feb',
       'Pesanggrahan15 Mar', 'Kebayoran Baru28 Feb', 'Pasar Minggu09 Mar',
       'Mampang Prapatan2 hari yang lalu', 'Kebayoran Lama08 Mar',
       'Kebayoran Lama14 Mar', 'Cilandak2 hari yang lalu',
       'CilandakKemarin', 'Cilandak04 Mar', 'Kebayoran Lama06 Mar',
       'Jakarta Selatan3 hari yang lalu', 'Pesanggrahan04 Mar',
       'Pancoran11 Jan', 'Cilandak06 Feb',
       'Kebayoran Baru3 hari yang lalu', 'Cilandak26 Feb',
       'Cilandak01 Mar', 'Kebayoran Baru10 Mar', 'Mampang Prapatan17 Mar',
       'Kebayoran Baru5 hari yang lalu', 'Cilandak6 hari yang lalu',
       'Jakarta Selatan15 Mar', 'Kebayoran Lama23 Feb',
       'Kebayoran BaruKemarin', 'Cilandak13 Mar', 'Pesanggrahan02 Mar',
       'Kebayoran Lama27 Feb', 'Kebayoran Baru16 Mar', 'Cilandak10 Mar',
       'Pesanggrahan28 Feb', 'Kebayoran Lama09 Mar',
       'Kebayoran Lama16 Mar', 'Kebayoran Baru05 Mar',
       'Jakarta Selatan13 Mar'], dtype=object)

In [ ]:
df['Locations'] = df['Locations'].str.replace('Hari ini', '').str.replace('hari yang lalu', '').str.replace('Kemarin', '')

In [ ]:
df['Locations'] = df['Locations'].str.replace(r'\d+ ', '', regex=True)

In [ ]:
df['Locations'].unique()

array(['Pasar Minggu', 'Pesanggrahan', 'Kebayoran Lama', 'Pancoran',
       'CilandakMar', 'Pasar MingguMar', 'Cilandak', 'Kebayoran Baru',
       'Mampang Prapatan', 'Kebayoran LamaFeb', 'Jakarta Selatan',
       'Kebayoran BaruMar', 'Kebayoran LamaDes', 'CilandakFeb',
       'Kebayoran LamaJan', 'Kebayoran LamaMar', 'Kebayoran BaruFeb',
       'Kebayoran BaruDes', 'Kebayoran BaruJan', 'Jakarta SelatanMar',
       'PesanggrahanMar', 'PancoranJan', 'Mampang PrapatanMar',
       'PesanggrahanFeb'], dtype=object)

In [ ]:
df['Locations'] = df['Locations'].str.replace(r'(Mar|Feb|Des|Jan)$', '', regex=True)

In [ ]:
df['Locations'].unique()

array(['Pasar Minggu', 'Pesanggrahan', 'Kebayoran Lama', 'Pancoran',
       'Cilandak', 'Kebayoran Baru', 'Mampang Prapatan',
       'Jakarta Selatan'], dtype=object)

In [ ]:
df

,Type,Price,Locations,Year,Kilometres
0,Daihatsu Sirion,Rp 125.000.000,Pasar Minggu,2017,155.000 - 160.000
1,Toyota Agya,Rp 109.000.000,Pesanggrahan,2019,30.000 - 35.000
2,Wuling Cortez,Rp 162.000.000,Kebayoran Lama,2021,55.000 - 60.000
3,Mitsubishi Outlander Sport,Rp 169.000.000,Pasar Minggu,2015,115.000 - 120.000
4,Honda Brio Satya,Rp 123.000.000,Pancoran,2017,85.000 - 90.000
...,...,...,...,...,...
509,Toyota Yaris,Rp 109.000.000,Kebayoran Lama,2012,90.000 - 95.000
510,Toyota Agya,Rp 100.000.000,Pancoran,2015,65.000 - 70.000
511,Suzuki Sidekick,Rp 75.000.000,Kebayoran Lama,1998,70.000 - 75.000
512,Toyota Yaris,Rp 113.000.000,Cilandak,2011,35.000 - 40.000
513,Nissan March,Rp 86.500.000,Cilandak,2012,90.000 - 95.000